/*
these are the reports we you can see how the game runs into the valorations of winners and losers
 */
package juego_1;

import static juego_1.interfaz_1.carre;
import static juego_1.panel.c1;
import static juego_1.panel.c12;
import static juego_1.panel.c2;
import static juego_1.panel.c23;
import static juego_1.panel.c3;
import static juego_1.panel.c34;
import static juego_1.panel.c4;
import static juego_1.panel.c45;
import static juego_1.panel.c5;
import static juego_1.panel.c56;
import static juego_1.panel.e1;
import static juego_1.interfaz_1.t11;
import static juego_1.interfaz_1.t22;
import static juego_1.interfaz_1.t33;
import static juego_1.interfaz_1.t44;
import static juego_1.interfaz_1.t55;


/**
 *
 * @author Kevin
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        this.setUndecorated(true);
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new java.awt.Label();
        l2 = new java.awt.Label();
        l3 = new java.awt.Label();
        l4 = new java.awt.Label();
        l5 = new java.awt.Label();
        b1 = new java.awt.Button();
        l7 = new javax.swing.JLabel();
        l9 = new java.awt.Label();
        l10 = new java.awt.Label();
        button1 = new java.awt.Button();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        bs = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        l2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        l3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        l4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        l5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        b1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b1.setLabel("Generar Reportes");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });

        l7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        l10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        button1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button1.setLabel("Borrar Reportes");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        l12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bs.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bs.setLabel("Salir");
        bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 258, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l16, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(l14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(170, 170, 170))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(l7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l9, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                        .addContainerGap(408, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l10, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked

        l1.setText(
                "El Nadador 1 ha ganado: " + c1);

        l2.setText(
                "El Nadador 2 ha ganado: " + c2);

        l3.setText(
                "El Nadador 3 ha ganado: " + c3);

        l4.setText(
                "El Nadador 4 ha ganado: " + c4);

        l5.setText(
                "El Nadador 5 ha ganado: " + c5);

        l7.setText(
                "Carreras Efectudas: " + carre);

        if (c1 > c2 & c1 > c3 & c1 > c4 & c1 > c5) {
            l10.setText("Ha ganado mas veces el Nadador 1");
        }
        if (c2 > c1 & c2 > c3 & c2 > c4 & c2 > c5) {
            l10.setText("Ha ganado mas veces el Nadador 2");
        }
        if (c3 > c2 & c3 > c1 & c3 > c4 & c3 > c5) {
            l10.setText("Ha ganado mas veces el Nadador 3");
        }
        if (c4 > c2 & c4 > c3 & c4 > c1 & c4 > c5) {
            l10.setText("Ha ganado mas veces el Nadador 4");
        }
        if (c5 > c2 & c5 > c3 & c5 > c4 & c5 > c1) {
            l10.setText("Ha ganado mas veces el Nadador 5");
        }
        if (c1 < c2 & c1 < c3 & c1 < c4 & c1 < c5) {
            l20.setText("Ha Perdido mas veces el Nadador 1");
        }
        if (c2 < c1 & c2 < c3 & c2 < c4 & c2 < c5) {
            l20.setText("Ha Perdido mas veces el Nadador 2");
        }
        if (c3 < c2 & c3 < c1 & c3 < c4 & c3 < c5) {
            l20.setText("Ha Perdido mas veces el Nadador 3");
        }
        if (c4 < c2 & c4 < c3 & c4 < c1 & c4 < c5) {
            l20.setText("Ha Perdido mas veces el Nadador 4");
        }
        if (c5 < c2 & c5 < c3 & c5 < c4 & c5 < c1) {
            l20.setText("Ha Perdido mas veces el Nadador 5");
        }

        l12.setText("Nadador 1 ha Perdido: " + c12);
        l13.setText("Nadador 2 ha Perdido: " + c23);
        l14.setText("Nadador 3 ha Perdido: " + c34);
        l15.setText("Nadador 4 ha Perdido: " + c45);
        l16.setText("Nadador 5 ha Perdido: " + c56);
        if (e1 == 0) {
            l9.setText("No hay en Empates en llegadas iguales");
        } else {
            l9.setText("Hay " + e1 + " Empates");
        }

    }//GEN-LAST:event_b1MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        c1 = 0;
        c2 = 0;
        c3 = 0;
        c4 = 0;
        c5 = 0;
        e1 = 0;
        carre = 0;
        c12 = 0;
        c23 = 0;
        c34 = 0;
        c45 = 0;
        c56 = 0;
        t11=false;
        t22=false;
        t33=false;
        t44=false;
        t55=false;
        l12.setText("Nadador 1 ha Perdido: " + c12);
        l13.setText("Nadador 2 ha Perdido: " + c23);
        l14.setText("Nadador 3 ha Perdido: " + c34);
        l15.setText("Nadador 4 ha Perdido: " + c45);
        l16.setText("Nadador 5 ha Perdido: " + c56);
        l1.setText(
                "El Nadador 1 ha ganado: " + c1);

        l2.setText(
                "El Nadador 2 ha ganado: " + c2);

        l3.setText(
                "El Nadador 3 ha ganado: " + c3);

        l4.setText(
                "El Nadador 4 ha ganado: " + c4);

        l5.setText(
                "El Nadador 5 ha ganado: " + c5);

        l10.setText("");
        l20.setText("");

        l7.setText(
                "Carreras Efectudas: " + carre);

        if (e1 == 0) {
            l9.setText("No hay en Empates en llegadas iguales");
        } else {
            l9.setText("Hay " + e1 + " Empates");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void bsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bsActionPerformed
    public void reporte() {

    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Button bs;
    private java.awt.Button button1;
    private java.awt.Label l1;
    private java.awt.Label l10;
    public static javax.swing.JLabel l12;
    public static javax.swing.JLabel l13;
    public static javax.swing.JLabel l14;
    public static javax.swing.JLabel l15;
    public static javax.swing.JLabel l16;
    private java.awt.Label l2;
    private javax.swing.JLabel l20;
    private java.awt.Label l3;
    private java.awt.Label l4;
    private java.awt.Label l5;
    private javax.swing.JLabel l7;
    private java.awt.Label l9;
    // End of variables declaration//GEN-END:variables
}
